server:
    port: 80

eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

#feign:
#    client:
#        config:
#            default:
#                connectTimeout: 1000  #单位毫秒
#                readTimeout: 1000

ribbon:
    ReadTimeout: 5000
logging:
    level:
#        feign日志以什么级别监控哪个接口
        com.atguigu.springcloud.service.PaymentFeignService: debug
